CREATE TABLE IF NOT EXISTS posts(id INT PRIMARY KEY AUTO_INCREMENT, message VARCHAR(400), dt VARCHAR(20));
CREATE TABLE IF NOT EXISTS contributor(userid INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(16));
